title: Ching Fhen
description: Leap Day is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal   # jekyll-theme-leap-day
some_url: https://chingfhen.github.io/portfolio0/another-page.html
links:
  linkedin: https://www.linkedin.com/in/chingfhen/