title: Ching Fhen
description: Leap Day is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
some_url: https://chingfhen.github.io/portfolio0/another-page.html
links:
  linkedin: https://www.linkedin.com/in/chingfhen/
contact:
  email: dsai.chingfhen@gmail.com
  phone: 97849200

about_me:
  name: Ching Fhen
  full_name: Tan Ching Fhen
  description: Experienced Data Scientist with half a decade of experience. Capable of delivering full stack AI Applications.